create extension if not exists pgcrypto;
create table users(id uuid primary key default gen_random_uuid(), email text unique not null, created_at timestamptz default now());
create table user_profiles(user_id uuid primary key references users on delete cascade, activity_profile text check (activity_profile in ('general','student','outdoor_worker','runner','cyclist','outdoor_sports','commuter')) default 'general', share_precise_location boolean default false);
create table saved_locations(id uuid primary key default gen_random_uuid(), user_id uuid references users on delete cascade, name text not null, latitude numeric(8,5) not null, longitude numeric(8,5) not null, created_at timestamptz default now());
create table stations(id text primary key, provider text not null, name text, latitude numeric(8,5), longitude numeric(8,5), source_url text);
create table air_observations(id bigserial primary key, location_id text, station_id text references stations, latitude numeric(8,5), longitude numeric(8,5), location_name text, pollutant text not null check (pollutant in ('pm25','pm10','no2','so2','o3')), concentration double precision, unit text not null default 'µg/m³', averaging_period text, observed_at timestamptz not null, retrieved_at timestamptz not null default now(), provider text not null, source_url text, quality_flag text, data_status text not null check (data_status in ('observed','estimated','modeled','cached','unavailable')), unique(location_id, pollutant, observed_at, provider));
create index on air_observations(location_id, pollutant, observed_at desc);
create table weather_observations(id bigserial primary key, location_id text, observed_at timestamptz not null, temperature double precision, relative_humidity double precision, wind_speed double precision, wind_direction double precision, pressure double precision, precipitation double precision, provider text not null, source_url text, retrieved_at timestamptz default now(), data_status text not null, unique(location_id, observed_at, provider));
create table forecast_models(model_id text primary key, model_type text, target text, feature_version text, horizon_hours int, training_start timestamptz, training_end timestamptz, trained_at timestamptz, dataset_size int);
create table model_metrics(id bigserial primary key, model_id text references forecast_models, split text, mae double precision, rmse double precision, r2 double precision, mape double precision, persistence_mae double precision);
create table forecasts(id bigserial primary key, location_id text, model_id text references forecast_models, target text, target_time timestamptz, prediction double precision, lower double precision, upper double precision, generated_at timestamptz default now());
create table anomaly_events(id bigserial primary key, location_id text, pollutant text, observed_at timestamptz, observed_value double precision, baseline double precision, score double precision, severity text, method text default 'rolling_robust_z');
create table environmental_sources(id serial primary key, name text, organization text, source_type text check (source_type in ('OFFICIAL','RESEARCH','NEWS','PUBLIC DATA')), base_url text);
create table environmental_events(id bigserial primary key, source_id int references environmental_sources, title text not null, organization text, event_date date, location text, category text, summary text, source_url text not null, retrieved_at timestamptz not null);
create table alerts(id uuid primary key default gen_random_uuid(), user_id uuid references users on delete cascade, location_id text, kind text, pollutant text, threshold double precision, frequency text, enabled boolean default true);
create table recommendations(id bigserial primary key, user_id uuid references users on delete set null, location_id text, activity text, window_start timestamptz, rating text, created_at timestamptz default now());
create table search_history(id bigserial primary key, user_id uuid references users on delete cascade, query text, created_at timestamptz default now());
create table exports(id bigserial primary key, user_id uuid references users on delete cascade, kind text, params jsonb, created_at timestamptz default now());
alter table saved_locations enable row level security;
alter table alerts enable row level security;
alter table user_profiles enable row level security;
alter table exports enable row level security;
alter table search_history enable row level security;
create policy own_rows on saved_locations using (user_id = auth.uid());
create policy own_rows on alerts using (user_id = auth.uid());
create policy own_rows on user_profiles using (user_id = auth.uid());
create policy own_rows on exports using (user_id = auth.uid());
create policy own_rows on search_history using (user_id = auth.uid());
